cellRangerPath:
  '/public/home/liuzj/softwares/environment/cellranger6'
cellRangerIndex:
  '/public/home/liuzj/data/singleCellRef/soybase_IPF'
resultDir:
  '/public/home/liuzj/projects/singleCell/soybean/02_result/20210922/'
pipelineDir:
  '/public/home/liuzj/projects/singleCell/soybean/02_result/20210922/'
genomeBed:
  '/public/home/liuzj/data/soybase_IPF/Glycine_max.Glycine_max_v2.1.46.gtf.changeTrsId.bed'
Samples:
  nodule_large:
    fastq:
      /public/home/liuzj/projects/singleCell/soybean/02_result/20210922/rawData/nodule_large/
    includeIntron:
      True
    expectCell:
      10000
    r2Length:
      91
  nodule_small:
    fastq:
      /public/home/liuzj/projects/singleCell/soybean/02_result/20210922/rawData/nodule_small/
    includeIntron:
      True
    expectCell:
      10000
    r2Length:
      91
  root:
    fastq:
      /public/home/liuzj/projects/singleCell/soybean/02_result/20210922/rawData/root/
    includeIntron:
      True
    expectCell:
      10000
    r2Length:
      91